### ISSUE TITLE
base import

### ISSUE THREAD

**Issue by TheChymera** [serebrov/so-questions#1]
Hi, what package is [this](https://github.com/serebrov/so-questions/blob/master/sql-alchemy/test_filter_by_joined_table.py#L9)? I don't think I have it

**Comment by serebrov** [comment]
It is in the same folder - https://github.com/serebrov/so-questions/blob/master/sql-alchemy/base.py.

**Comment by serebrov** [comment]
But actually, I only keep it because of `to_dict()` method, so I can easily print sqlalchemy models. You should be able to just use the `Base = declarative_base()` directly.

**Comment by TheChymera** [comment]
Thank you :)
